#!/bin/sh

revision="Car Play activation v0.1.2 (2021-02-22 by MIBonk)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
	echo -ne "\n$ME-$thisname---->\n" >> $LOG
fi

if [ -f $TMP/reboot.mib ]; then
	echo "Reboot running..."
	return 2> /dev/null
fi

	case $1 in

	-a) {

[ -z "$GEM" ] && echo -ne "\033[36m"
echo -ne "CarPlay and Android Auto activated now\n" | $TEE -a $LOG
[ -z "$GEM" ] && echo -ne "\n"
[ -z "$GEM" ] && echo -ne "\033[m"
if [[ "$TRAINVERSION" = *CN* ]]; then
	echo -ne "BAIDU CarLife activated now\n" | $TEE -a $LOG
	on -f mmx $PC b:0:3221356628:7.6 1 2>> $LOG
fi
on -f mmx $PC b:0:3221356628:7.7 1 2>> $LOG
on -f mmx $PC b:0:3221356628:8.0 1 2>> $LOG
on -f mmx $PC b:0:3221356628:8.5 1 2>> $LOG
on -f mmx $PC i:0:1343769792 3 2>> $LOG
on -f mmx $PC b:0:1 0 2>> $LOG

. $thisdir/reboot -t 10

return 2> /dev/null

	};;

	-b) {

[ -z "$GEM" ] && echo -ne "\033[36m"
echo -ne "CarPlay and Android Auto activated now\n" | $TEE -a $LOG
[ -z "$GEM" ] && echo -ne "\n"
[ -z "$GEM" ] && echo -ne "\033[m"
if [[ "$TRAINVERSION" = *CN* ]]; then
	echo -ne "BAIDU CarLife activated now\n" | $TEE -a $LOG
	on -f mmx $PC b:0:3221356628:7.6 1 2>> $LOG
fi
on -f mmx $PC b:0:3221356628:7.7 1 2>> $LOG
on -f mmx $PC b:0:3221356628:8.0 1 2>> $LOG
on -f mmx $PC b:0:3221356628:8.5 1 2>> $LOG
on -f mmx $PC i:0:1343769792 3 2>> $LOG
on -f mmx $PC b:0:1 0 2>> $LOG

return 2> /dev/null

	};;

	-s) {

[ -z "$GEM" ] && echo -ne "\033[36m"
echo -ne "CarPlay and Android Auto Status\n\n" | $TEE -a $LOG
[ -z "$GEM" ] && echo -ne "\033[m"
echo -ne "\nCarplay: " | $TEE -a $LOG
on -f mmx $PC b:0:3221356628:8.0 | $TEE -a $LOG
echo -ne "\nAndroid Auto: " | $TEE -a $LOG
on -f mmx $PC b:0:3221356628:7.7 | $TEE -a $LOG
echo -ne "\nUSB Status: " | $TEE -a $LOG
on -f mmx $PC i:0:1343769792 | $TEE -a $LOG
	
return 2> /dev/null

	};;	
	

	# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" [OPTION]"
		echo ""
		echo "Options:"
		echo "        -a 			activated"
		echo "        -b 			activated - no reboot"
		echo "        -s 			status"
		echo "        --help			show this help"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""

	};;

	esac

exit 0
