#!/bin/sh

revision="crcr16/CCITT-False v0.1.1 (2021-02-22 by MIBonk)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
	echo -ne "\n$ME-$thisname---->\n" >> $LOG
fi

if [ -f $TMP/reboot.mib ]; then
	echo "Reboot running..."
	return 2> /dev/null
fi

if [ ! -z $1 ]; then
	VALUE=patch
else
	VALUE=""
fi

	case $VALUE in

	patch) {

input=$1

string=$(echo $input | $SED "s/.\{2\}/&:/g" | awk '{print toupper($0)}')
byte=$(echo "${string}" | awk -F ":" '{print NF-1}')
polynom=$(echo "ibase=16; 1021" | $BC) #0x1021 CCITT Polynom
crcsum=$(echo "ibase=16; FFFF" | $BC) #0xFFFF"
xorout=$(echo "ibase=16; FFFF" | $BC) #0xFFFF"

echo -ne "Generate crc16/CCITT-False checksum..." | $TEE -a $LOG
[ -n "$GEM" ] && echo -ne "\n"
count=1
while [ ${count} -le $byte ]
do
	[ -z "$GEM" ] && echo -n "."
	echo -n "." >>$LOG
	hex=$(echo $string | awk -F : -v i=$count '{print $i}')
	dec=$(echo "ibase=16; $hex" | $BC)
	bin=$(echo "obase=2; ibase=16; $hex" | $BC)
	bin=$(echo "00000000"${bin} | tail -c9)
	crcsum=$(($crcsum ^ $(echo "$dec * 2 ^ 8" | $BC)))
	bit=0
	while [ $bit -lt 8 ]
	do
		result=$((crcsum <<= 1))
		if [ $result -ge "65536" ];then
			crcsum=$(($result ^ $polynom))
		fi
			crcsum=$((crcsum &= $xorout))
		bit=$(($bit+1))
	done
	count=$(($count+1))
done

crcsum="$(echo "ibase=10; obase=16; 2^16+$crcsum" | $BC | cut -c 2-)"
echo -ne " and the Winner is: " >> $LOG
[ -z "$GEM" ] && echo -ne $crcsum"\n\n"
echo -ne $crcsum"\n\n" >> $LOG


return 2> /dev/null

	};;

	# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" [OPTION]"
		echo ""
		echo "Options:"
		echo "        <string> 		Hex String"
		echo "        --help			show this help"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""

	};;

	esac

$thisdir/mounts -r

exit 0
