#!/bin/sh

revision="javag24 v0.2.3 (2022-07-09 MIB-Wiki)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
	echo -ne "\n$ME-$thisname---->\n" >> $LOG
fi

if [ -f $TMP/backup.mib ] || [ -f $TMP/reboot.mib ] || [ -f $TMP/flash.mib ]; then
	echo "Backup or reboot is already running..."
	return 2> /dev/null
fi

if [ "$2" = "-noboot" ]; then
	noboot=$2
else
	noboot=""
fi

APP="/net/mmx/mnt/app/eso/hmi/lsd/jars/"
JAR="g24ws.jar"

case $1 in

-on) {

trap '' 2

	echo -ne "Enable widescreen CarPlay and AndroidAuto on G24\n"
	if [[ "$TRAINVERSION" = *POG24* ]] || [[ "$TRAINVERSION" = *BYG24* ]]; then
		if [ -f $APP$JAR ]; then
			echo -ne "File already present on unit. Will be replaced\n" | $TEE -a $LO
		fi
		mount -uw /net/mmx/mnt/app
		cp -r $VOLUME/mod/java/$JAR $APP$JAR 2>> $LOG
		mount -ur /net/mmx/mnt/app
		[ -z "$noboot" ] && . $thisdir/reboot -t 10
	else
		echo -ne "no supported train found - will stop here\n" | $TEE -a $LOG
	fi

trap 2

return 2> /dev/null

};;

-off) {

trap '' 2

	echo -ne "Remove widescreen CarPlay and AndroidAuto support from G24\n"
	if [[ "$TRAINVERSION" = *POG24* ]] || [[ "$TRAINVERSION" = *BYG24* ]]; then
		if [ -f $APP$JAR ]; then
			mount -uw /net/mmx/mnt/app
			rm -rf $APP$JAR 2>> $LOG
			mount -ur /net/mmx/mnt/app
			[ -z "$noboot" ] && . $thisdir/reboot -t 10
		else
				echo -ne "File not found - widescreen patch is not installed\n" | $TEE -a $LOG
		fi
	else
		echo -ne "no supported train found - will stop here\n" | $TEE -a $LOG
	fi

trap 2

return 2> /dev/null

};;

# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" [OPTION1] [-noboot]"
		echo ""
		echo "Option 1:"
		echo "        -on 		enable CP/AA widescreen support"
		echo "        -off 		remove CP/AA widescreen support"
		echo "        --help		show this help"
		echo ""
		echo "Option 2:"
		echo "        -noboot	no reboot triggered by script"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""
		
	};;
	
	esac

exit 0

