#!/bin/sh

revision="listgfcache v0.1.0 (2026-04-05 by PTP)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
	echo -ne "\n$ME-$thisname---->\n" 2>> $LOG
fi

if [ -f $TMP/reboot.mib ]; then
	echo "Reboot running..."
	return 2> /dev/null
fi

trap '' 2

	case $1 in

	-l) {

echo -ne "Listing content of /net/mmx/mnt/gecache ...\n\n"
sleep 1
if [[ "$TRAINVERSION" = *MHI2Q* ]]; then
	echo -ne "MHI2Q unit not supported\n" | $TEE -i -a $LOG
	echo -ne "will stop here - go back\n"
else
    ls -la /net/mmx/mnt/gecache

	echo -ne "\nThat´s it!\n"
fi

trap 2

return 2> /dev/null

	};;

	-e) {

echo -ne "Emptying content of /net/mmx/mnt/gecache ...\n\n"
sleep 1
if [[ "$TRAINVERSION" = *MHI2Q* ]]; then
	echo -ne "MHI2Q unit not supported\n" | $TEE -i -a $LOG
	echo -ne "will stop here - go back\n"
else
    rm -rf /net/mmx/mnt/gecache/*
	on -f mmx sync
	sleep 3
	echo -ne "\nThat´s it!\n"
    . $thisdir/reboot -t 10
fi

trap 2

return 2> /dev/null

	};;

	# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" [OPTION]"
		echo ""
		echo "Options:"
		echo "        -l			    list Nav Cache"
		echo "        -e			    empty Nav Cache"
		echo "        --help			show this help"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""

	};;

	esac

exit 0
