#!/bin/sh

revision="settrain v0.1.9 (2023-05-16 by MIB-Wiki)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
fi
echo -ne "\n$ME-$thisname---->\n" | $TEE -i -a $LOG

if [ -f $TMP/reboot.mib ]; then
	echo -ne "Aborted because the reboot is running...\n"
	return 2> /dev/null
fi

if [ "$2" = "-noboot" ]; then
	noboot=$2
else
	noboot=""
fi

case $1 in
	-eu) {
		trap '' 2
		echo -ne "Current train: $TRAINVERSION\n" | $TEE -i -a $LOG
		echo -ne ""
		if [[ "$TRAINVERSION" = *ER* ]]; then
			echo -ne "Skipping. Your train is already EU!\n" | $TEE -i -a $LOG
		else
			echo -ne "Non EU train found, will try to find an EU match.\nCreating backup...\n" | $TEE -i -a $LOG
			
			# Do the backup before conversion
			. $thisdir/backup -a
			TARGETTRAIN=""
			if [[ "$TRAINVERSION" = *MHI2Q* ]] && [[ "$TRAINVERSION" = *AUG22* ]]; then
				TARGETTRAIN="MHI2Q_ER_AUG22_P5092"
				echo -ne "MHI2Q_ER_AUG22 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 51 5f 45 52 5f 41 55 47 32 32 5f 50 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 35 30 39 32 00 >> $LOG
			elif [[ "$TRAINVERSION" = *SKG13* ]]; then
				TARGETTRAIN="MHI2_ER_SKG13_P4526"
				echo -ne "SKG13 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 53 4b 47 31 33 5f 50 34 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 35 32 36 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *VWG11* ]] || [[ "$TRAINVERSION" = *CN_VW48x_?06* ]] || [[ "$TRAINVERSION" = *JP_VW48x_?06* ]]; then
				TARGETTRAIN="MHI2_ER_VWG11_K3342"
				echo -ne "VWG11 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 56 57 47 31 31 5f 4b 33 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 33 34 32 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *VWG13* ]] || [[ "$TRAINVERSION" = *JP_VW48x_?07* ]] || [[ "$TRAINVERSION" = *CN_VW48x_?08* ]] || \
			[[ "$TRAINVERSION" = *CN_VW48x_?09* ]] || [[ "$TRAINVERSION" = *CN_VW48x_?10* ]] || [[ "$TRAINVERSION" = *CN_VW48x_?11* ]] || \
			[[ "$TRAINVERSION" = *CN_VW48x_?12* ]] || [[ "$TRAINVERSION" = *JP_VW48x_?08* ]] || [[ "$TRAINVERSION" = *JP_VW48x_?09* ]] || \
			[[ "$TRAINVERSION" = *JP_VW48x_?10* ]] || [[ "$TRAINVERSION" = *JP_VW48x_?11* ]] || [[ "$TRAINVERSION" = *JP_VW48x_?12* ]] || \
			[[ "$TRAINVERSION" = *TW_VW48x_?07* ]] || [[ "$TRAINVERSION" = *TW_VW48x_?09* ]] || [[ "$TRAINVERSION" = *TW_VW48x_?11* ]] || \
			[[ "$TRAINVERSION" = *CN_VW511_?10* ]]; then
				TARGETTRAIN="MHI2_ER_VWG13_P4521"
				echo -ne "VWG13 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 56 57 47 31 33 5f 50 34 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 35 32 31 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *POG11* ]]; then
				TARGETTRAIN="MHI2_ER_POG11_K5126"
				echo -ne "POG11 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 50 4f 47 31 31 5f 4b 35 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 31 32 36 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *POG24* ]]; then
				TARGETTRAIN="MHI2_ER_POG24_K4224"
				echo -ne "POG24 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 50 4f 47 32 34 5f 4b 34 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 32 32 34 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *AU37x* ]]; then
				TARGETTRAIN="MHI2_ER_AU37x_P5089"
				echo -ne "AU37x train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4D 48 49 32 5F 45 52 5F 41 55 33 37 78 5F 50 35 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 30 38 39 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *AU43x* ]]; then
				TARGETTRAIN="MHI2_ER_AU43x_P5098"
				echo -ne "AU43x train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4D 48 49 32 5F 45 52 5F 41 55 34 33 78 5F 50 35 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 30 39 38 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *AU57x* ]] || [[ "$TRAINVERSION" = *AUG11* ]]; then
				TARGETTRAIN="MHI2_ER_AU57x_K3663"
				echo -ne "AU57x train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 41 55 35 37 78 5f 4b 33 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 36 36 33 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *AU62x* ]]; then
				TARGETTRAIN="MHI2_ER_AU62x_P5099"
				echo -ne "AU62x train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 41 55 36 32 78 5f 50 35 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 30 39 39 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *AU276* ]]; then
				TARGETTRAIN="MHI2_ER_AU276_P5088"
				echo -ne "AU276 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 41 55 32 37 36 5f 50 35 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 30 38 38 00 00 >> $LOG
			elif [[ "$TRAINVERSION" = *AUG22* ]]; then
				TARGETTRAIN="MHI2_ER_AUG22_K3346"
				echo -ne "AUG22 train found. Changing to $TARGETTRAIN\n" | $TEE -i -a $LOG
				on -f rcc /usr/apps/modifyE2P w 3a0 4d 48 49 32 5f 45 52 5f 41 55 47 32 32 5f 4b 33 >> $LOG
				on -f rcc /usr/apps/modifyE2P w 3b0 33 34 36 00 00 >> $LOG
			else
				echo -ne "\n\nAborted. Unknown train\nTo add support, upload backup to https://mibsolution.one M.I.B_Backup\n" | $TEE -i -a $LOG
				exit 1
			fi
			echo -ne "\nAll done! Now you can reboot the unit and install $TARGETTRAIN\n" | $TEE -i -a $LOG
		fi
		trap 2
		[ -z "$noboot" ] && . $thisdir/reboot -t 10
	};;

	# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" [OPTION] [-noboot]"
		echo ""
		echo "Options:"
		echo "        -eu           set Train to EU"
		echo "        --help        show this help"
		echo ""
		echo "Note: Backup will only work in RCC bash!"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""
	};;
esac
exit 0