#!/bin/sh

revision="showimage v0.1.2 (2023-04-14 by Mib-Wiki)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
	echo -ne "\n$ME-$thisname---->\n" >> $LOG
fi

	case $1 in

	-load) {
# <duration in s> <path> <filename>
# supported image formats: /
# jpeg, png, gif (no animations), bmp

trap '' 2

# echo "displaying ${4}"

export LIBIMG_CFGFILE=/etc/imgprocessing.cfg
LD_LIBRARY_PATH=/eso/lib:/armle/lib:/root/lib-target:/armle/lib/dll /eso/bin/apps/loadandshowimage ${3}${4}&

/net/mmx/eso/bin/apps/dmdt sc 0 -9 | $TEE -a $LOG # trigger display of image

#sleep 1
#/net/mmx/eso/bin/apps/dmdt ts 0 "/net/mmx/fs/sda0/screenshot_$4" | $TEE -a $LOG # take screenshot of doslpay output

sleep $2

LD_LIBRARY_PATH=/eso/lib:/armle/lib:/root/lib-target /eso/bin/apps/loadandshowimage 1 2 3 4 5 
/net/mmx/eso/bin/apps/dmdt sb 0 | $TEE -a $LOG # switch back to standard output screen

trap 2

return 2> /dev/null

};;

	-ts) {
# Take a screenshot from screen 0 and dump to *.png file
# <time until screenshot> <file name appendix>
trap '' 2

if [ -z $2 ]; then
	sleep 0
else
	sleep $2
fi

ID=$(/net/rcc/usr/bin/date +%Y_%m_%d_%H_%M_%S)

/net/mmx/eso/bin/apps/dmdt ts 0 "/net/mmx/fs/sda0/SCREENSHOT_${3}${ID}.png"

return 2> /dev/null

};;

	# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" "
		echo ""
		echo "Options:"
		echo "        -load 	[DURATION] [PATH] [FILE]			loads defined image to screen"
		echo "        -ts 	[time [s] until screenshot]	[file name appendix]	takes a screenshot of main screen"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""

	};;

	esac

exit 0
