#!/bin/sh

revision="Audi subwoofer control v0.1.0 (2023-02-05 by Mib-Wiki)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
	echo -ne "\n$ME-$thisname---->\n" >> $LOG
fi

AMP="$(on -f mmx $PC i:0:0x50182CFF)" # long coding byte 11
DSPERS="$(on -f mmx /eso/bin/dumb_persistence_reader 0 3221422112)" #0x3B00
DSNOSUB="004064F70009F70009F70009000000000000000000F700090000000002070102001E262E373F474F5764707D8995A6B6C7DBF03131CBBE"
DSSUBON="004064F70009F70009F70009000000000000000000F70009F700090002070102001E262E373F474F5764707D8995A6B6C7DBF03131D568"

if [[ "$TRAINVERSION" = *AU* ]]; then
VALUE=$1
else
VALUE="-stop"
echo -ne "Wrong brand, this unit is not AUDI!\n" | $TEE -a $LOG
return 2> /dev/null
fi

if [ "$AMP" = 2 ]; then
	echo -ne "External sound system coding found!\nWe will stop here, as this patch can only be applied to units with 5F internal sound system\n" | $TEE -a $LOG
	sleep 2
	return 2> /dev/null
else
	echo -ne "No external sound system coding found!\n" | $TEE -a $LOG
fi

if [ -f $TMP/reboot.mib ]; then
	echo "Reboot running..."
	return 2> /dev/null
fi

	case $VALUE in

	-subon) {

trap '' 2

[ -z "$GEM" ] && echo -ne "\033[36m"
echo -ne "Install SUBWOOFER dataset\n" | $TEE -a $LOG
[ -z "$GEM" ] && echo -ne "\033[m"

if [ "$DSPERS" = "$DSNOSUB" ]; then
	echo -ne "ORIGINAL dataset found on unit\n" | $TEE -a $LOG
	echo -ne "Installing SUBWOOFER patch\n" | $TEE -a $LOG
	on -f mmx $PC b:0:3221422112 $DSSUBON 2>> $LOG
	on -f mmx $PC b:0:1 0 2>> $LOG
	echo -ne "DONE\n" | $TEE -a $LOG
	trap 2
	. $thisdir/reboot -t 10
else
	echo -ne "No ORIGINAL dataset found on unit\n" | $TEE -a $LOG
	echo -ne "Go BACK\n" | $TEE -a $LOG
	trap 2
fi	

return 2> /dev/null

	};;

	-suboff) {

trap '' 2

[ -z "$GEM" ] && echo -ne "\033[36m"
echo -ne "Install ORIGINAL dataset\n" | $TEE -a $LOG
[ -z "$GEM" ] && echo -ne "\033[m"

if [ "$DSPERS" = "$DSSUBON" ]; then
	echo -ne "SUBWOOFER patch found on unit\n" | $TEE -a $LOG
	echo -ne "Installing ORIGINAL dataset\n" | $TEE -a $LOG
	on -f mmx $PC b:0:3221422112 $DSNOSUB 2>> $LOG
	on -f mmx $PC b:0:1 0 2>> $LOG
	echo -ne "DONE\n" | $TEE -a $LOG
	trap 2
	. $thisdir/reboot -t 10
else
	echo -ne "No ORIGINAL dataset found on unit\n" | $TEE -a $LOG
	echo -ne "Go BACK\n" | $TEE -a $LOG
	trap 2
fi	

return 2> /dev/null

	};;


	# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" [OPTION]"
		echo ""
		echo "Options:"
		echo "        -subon 			Install SUBWOOFER patch"
		echo "        -suboff 			Install ORIGINAL dataset (disable subwoofer control)"
		echo "        --help			show this help"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""

	};;

	esac

exit 0
